### PR TITLE
update pt_br.json

### PR DESCRIPTION
**Pull request by AndreAugustoDev**
## Proposed Changes

- Updates some words from the translation added by PR #5
- Some words don't have a solid meaning and are probably taken directly from GTranslator
- Revisions requested in the quoted PR were made in my commit

## Additional Context
PR #5 needs to merged before this

### CODE REVIEW

**Comment by rlnt** [comment]
Oh dear, I don't speak Portuguese so I rely on contributions from the community. I only spot-check the submitted translations with a translator, but of course, it takes more than that to get the grammar and spelling right.

Seems like you are both from Brazil.

@FITFC do you agree with those changes?

**Comment by FITFC** [comment]
Yes, I agree, I used Gtranslate to help, but I made some adjustments to make it better, but if it has a better translation, it can be implemented :D

**Comment by rlnt** [comment]
@AndreAugustoAAQ Please rebase your branch onto the 1.19-forge branch to include the changes from the other PR.

**Comment by rlnt** [comment]
Thanks for the contribution!

**Pull request merged**
